Voice xp limit
IIoW/IIslander pull request #172
Opened 2022-01-20 22:21 UTC by KommentatorForAll

Added a limit to voice xp of 3 hours of whatever one is doing. 
this avoids afk problems.

2022-01-21 05:40 UTC, Chicken requested changes

2022-01-21 05:40 UTC, Chicken commented on src/modules/leveling/voice/voice.js
> +    const xpToGive = Math.max(
Shouldn't this be `Math.min()`
```suggestion
    const xpToGive = Math.min(
```

2022-01-24 05:04 UTC, Chicken approved these changes

2022-01-24 05:27 UTC, WilsontheWolf approved these changes

2022-01-24 05:27 UTC, merged